developerProject/force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>Email</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

developerProject/force-app/main/default/objects/Email__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email_Address</label>
    <type>Email</type>
</CustomField>

developerProject/force-app/main/default/objects/Email__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <label>Email_Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

developerProject/force-app/main/default/objects/Email__c/fields/Email_Object__c.field-meta.xml
<CustomField>
    <fullName>Email_Object__c</fullName>
    <label>Email_Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/classes/EmailSend.cls
public class EmailSend {
    public Email__c mapping_rec_Email {get; set;}
    
      public Attachment attachment {
  get {
      if (attachment == null)
        attachment = new Attachment();
      return attachment;
    }
  set;
  }
    
    public void Init(){
        mapping_rec_Email = new Email__c();

    }
    public void sent_email(){   
		EmailManager em = new EmailManager();
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName(attachment.Name);
        efa.setBody(attachment.Body);
        //em.sendMail('zhangyushan0412@outlook.com', 'aaaa', 'bbbbb',efa);
        em.sendMail(mapping_rec_Email.Email_Address__c, mapping_rec_Email.Email_Object__c, mapping_rec_Email.Email_Body__c,efa);
    }    



}