developerProject/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

developerProject/force-app/main/default/objects/Loan_Details__c/Loan_Details__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Loan_Details</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan_Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

developerProject/force-app/main/default/objects/Loan_Details__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <label>Applicant_Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/objects/Loan_Details__c/fields/Drivers_Licence_Number__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Licence_Number__c</fullName>
    <label>Drivers_Licence_Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/classes/LoanDetails.cls
public with sharing class LoanDetails {
	
	public list<Loan_Details__c> Loan_Details {get; set;}
   
    public Loan_Details__c mapping_rec {get; set;}
   
    public LoanDetails(){
        
    }
    public void Init(){
        
        Loan_Details = [select id, Address__c, Applicant_Name__c, Drivers_Licence_Number__c from Loan_Details__c];
        
        if(Loan_Details != null && !Loan_Details.IsEmpty() && Loan_Details.size() >0){
        
            mapping_rec = Loan_Details[0];
        }else{
            mapping_rec = new Loan_Details__c();
        }    
    }    
   
    public void save(){
        
        upsert mapping_rec;
        
    }
   
    public void newRecord(){
        
        mapping_rec = new Loan_Details__c();
        
    }
    
}