developerProject/force-app/main/default/objects/Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Application Number</label>
    <type>AutoNumber</type>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/Asset_type__c.field-meta.xml
<CustomField>
    <fullName>Asset_type__c</fullName>
    <label>Asset type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Plant and Equipment</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LEAP Legal</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Telecoms</fullName>
            </value>
            <value>
                <fullName>Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/No_Of_Payments__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Payments__c</fullName>
    <label>No Of Payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Under Assessment</fullName>
            </value>
            <value>
                <fullName>Approved-Pending further info</fullName>
            </value>
            <value>
                <fullName>Approved - Waiting on Invoice</fullName>
            </value>
            <value>
                <fullName>In for Settlement</fullName>
            </value>
            <value>
                <fullName>Out for Signing</fullName>
            </value>
            <value>
                <fullName>Signed Documents</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Line_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Line_Item__c.Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

developerProject/force-app/main/default/objects/Application__c/fields/Total_Amount_and_GST__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_and_GST__c</fullName>
    <formula>Total_Amount__c  *  (1+ GST__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount and GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/Application_Applicant__c.object-meta.xml
<CustomObject>
    <label>Application Applicant</label>
    <nameField>
        <label>Application Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Applicants</relationshipLabel>
    <relationshipName>Application_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

developerProject/force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>Email</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

developerProject/force-app/main/default/objects/Email__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email_Address</label>
    <type>Email</type>
</CustomField>

developerProject/force-app/main/default/objects/Email__c/fields/Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Body__c</fullName>
    <label>Email_Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

developerProject/force-app/main/default/objects/Email__c/fields/Email_Object__c.field-meta.xml
<CustomField>
    <fullName>Email_Object__c</fullName>
    <label>Email_Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/objects/Line_Item__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

developerProject/force-app/main/default/classes/ApplicationProcess.cls
public with sharing class ApplicationProcess {
	
	public list<Application__c> Application {get; set;}
	public list<Application_Applicant__c> Application_Applicant {get; set;}
	public list<Line_Item__c> Line_Item {get; set;}

    public Application_Applicant__c mapping_rec {get; set;}
	public Application__c mapping_rec_Application {get; set;}
	public Line_Item__c mapping_rec_Line_Item {get; set;}
    public Email__c mapping_rec_Email {get; set;}
	
    public Boolean bApplication{get;set;}
    public Boolean bApplication_Applicant{get;set;}
    public Boolean bLine_Item{get;set;}    
        // value
    public double i =0;

    
    public ApplicationProcess(){
    	bApplication= true;
    	bApplication_Applicant=false;
    	bLine_Item=false;        
    }
  
    public void Init(){    	
        Application = [select id,Application_Number__c, Asset_type__c, Comments__c, 
                       Company_Name__c,Contract_Amount__c,Customer_type__c,Frequency__c,
                       No_Of_Payments__c,Status__c,Total_Amount__c,GST__c ,Total_Amount_and_GST__c
                       from Application__c];
        
        if(Application != null && !Application.IsEmpty() && Application.size() >0){
            mapping_rec_Application = Application[0];
        }else{
            mapping_rec_Application = new Application__c();
            mapping_rec_Application.GST__c = Custom_Setting.getGST();
        }
        mapping_rec = new Application_Applicant__c();
        mapping_rec_Line_Item = new Line_Item__c();
        mapping_rec_Email = new Email__c();
    }
    public PageReference save(){
        if(IsEmptyFieldExists()){
            return null;
    	}
        upsert mapping_rec_Application;
        return null;
    }
   
    public PageReference save_new(){
    	if(IsEmptyFieldExists()){
    		return null;
    	}
        upsert mapping_rec_Application;
        mapping_rec.Application__c=mapping_rec_Application.Id;	
        upsert mapping_rec;
        mapping_rec_Line_Item.Application__c= mapping_rec_Application.Id;	
        upsert mapping_rec_Line_Item;
        newRecord();
        i=0;
        switch_page();
        return null;
    }
  
    public PageReference next(){
    	i++;
        switch_page();
        return null;
    }
  
    public PageReference previous(){
    	i--;
        switch_page();
        return null;
    }
  
    public void switch_page(){
        system.debug('abbbbbbbbbbbb');
        if (i ==0){
            bApplication= true;
            bApplication_Applicant= false;
            bLine_Item= false;        
            
        }else if (i ==1){
            bApplication= false;
            bApplication_Applicant= true;
            bLine_Item= false;
    	}else if(2==i){
    		bApplication= false;
    		bApplication_Applicant= false;
    		bLine_Item= true;
    	}
    }
    
    public void newRecord(){   
        mapping_rec_Application = new Application__c();
        mapping_rec = new Application_Applicant__c();
        mapping_rec_Line_Item = new Line_Item__c();
        mapping_rec_Application.GST__c = Custom_Setting.getGST();
        }
        
    public void sent_email(){   
		EmailManager em = new EmailManager();
    // Reference the attachment page and pass in the account ID
    PageReference pdf = Page.attachmentPDF;
    pdf.getParameters().put('id',(String)ApexPages.currentPage().getParameters().get('id'));
    pdf.setRedirect(true);
    // Take the PDF content
    Blob b = pdf.getContent();
    // Create the email attachment
    Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
    efa.setFileName('attachment.pdf');
    efa.setBody(b);
		em.sendMail(mapping_rec_Email.Email_Address__c, mapping_rec_Email.Email_Object__c, mapping_rec_Email.Email_Body__c,efa);
        system.debug('aaaaaaaaaaaaa '+mapping_rec_Email.Email_Address__c);
        }     
    
    public boolean IsEmptyFieldExists(){
        boolean IsEmpty = false;  
		if(mapping_rec_Line_Item != null && 
		0 == mapping_rec_Line_Item.Quantity__c){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
			GlobalConstant.INCOMPLETE));
			IsEmpty = true;
		}
		return  IsEmpty;
	}    
    
}