developerProject/force-app/main/default/objects/Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/Application_Applicant__c.object-meta.xml
<CustomObject>
    <label>Application Applicant</label>
    <nameField>
        <label>Application Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Applicants</relationshipLabel>
    <relationshipName>Application_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Business_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Business_Address_City__c</fullName>
    <label>Business Address City</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Business_Address_PostCode__c.field-meta.xml
<CustomField>
    <fullName>Business_Address_PostCode__c</fullName>
    <label>Business Address PostCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Business_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Business_Address_State__c</fullName>
    <label>Business Address State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Business_Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Business_Address_Street__c</fullName>
    <label>Business Address Street</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Professionals</fullName>
            </value>
            <value>
                <fullName>Major Corporate</fullName>
            </value>
            <value>
                <fullName>Medium Corporate</fullName>
            </value>
            <value>
                <fullName>Associations &amp; Clubs</fullName>
            </value>
            <value>
                <fullName>Private Schools</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

developerProject/force-app/main/default/objects/Application_Applicant__c/fields/Years_in_Business__c.field-meta.xml
<CustomField>
    <fullName>Years_in_Business__c</fullName>
    <label>Years in Business</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

developerProject/force-app/main/default/classes/Application_Applicant.cls
public with sharing class Application_Applicant {
	
	public list<Application_Applicant__c> Application_Applicant {get; set;}
//  	public list<Application_Applicant__c> Application_Applicant {get; set;}

   
    public Application_Applicant__c mapping_rec {get; set;}
    //   	public Application_Applicant__c mapping_rec_Applicant {get; set;}
   	
    public Application_Applicant(){
        
    }
    
    public void Init(){
    	
        
        Application_Applicant = [select id,ABN__c, Business_Name__c, Business_Type__c, 
                                 Business_Address_Street__c,Business_Address_State__c,
                                 Business_Address_PostCode__c,Business_Address_City__c, 
                                 Primary_Applicant__c,Years_in_Business__c,Application__c
                                 from Application_Applicant__c];
        
        if(Application_Applicant != null && !Application_Applicant.IsEmpty() && Application_Applicant.size() >0){
        
            mapping_rec = Application_Applicant[0];
        }else{
            mapping_rec = new Application_Applicant__c();
        }    
    }    
   
    public void save(){
        
        upsert mapping_rec;
        
    }
   
    public void newRecord(){
        
        mapping_rec = new Application_Applicant__c();
        
    }
    
}