developerProject/force-app/main/default/objects/Custom_Setting__c/Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Setting</label>
</CustomObject>

developerProject/force-app/main/default/objects/Custom_Setting__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <defaultValue>0.10</defaultValue>
    <label>GST</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

developerProject/force-app/main/default/classes/Custom_Setting.cls
public with sharing class Custom_Setting {   
    
    public static Custom_Setting__c     Custom_Setting;
    public static void LoadCustomSettingsdata(){
        Custom_Setting = Custom_Setting__c.getInstance();
    }
    // because there's a static, we can access to the function
    
    public static double getGST(){
        LoadCustomsettingsdata();    
        return Custom_Setting.GST__c * 100;
    }
    
    public static void setCustomSettings(Custom_Setting__c CustomSetting){
        Custom_Setting = CustomSetting;
    }    
}